language: rust
sudo: false
cache: 
  - cargo
  - pip
install: 
  - $HOME/.cargo/bin/mdbook -V || cargo install mdbook
  - pip install --user ghp-import
script: $HOME/.cargo/bin/mdbook build
deploy:
  provider: script
  on:
    branch: master
  script: scripts/deploy.sh
  skip_cleanup: true
